### ISSUE TITLE
Dark/Light Theme Toggler

### ISSUE THREAD

**Issue by iamakhileshmishra** [jay-2000/Open-source-hacktoberfest#20]
I would like to add a localstorage based dark/light theme toggler please assign this to me under hacktoberfest

**Comment by jay-2000** [comment]
> I would like to add a localstorage based dark/light theme toggler please assign this to me under hacktoberfest

sure @iamakhileshmishra go ahead

**Comment by iamakhileshmishra** [comment]
I have added please accept it

**Comment by jay-2000** [comment]
> I have added please accept it

Done 
Don't forget to star this project.
