### ISSUE TITLE
feat: Vertical Image Slider Mini Project

### ISSUE THREAD

**Issue by RoshanMhatre** [jay-2000/Open-source-hacktoberfest#33]
### Vertical Image Slider
I have developed a vertical image slider using HTML5, CSS3, and vanilla JS.
Please assign this issue to me and add the 'hacktoberfest-accepted' label to avoid any issues.

**Comment by jay-2000** [comment]
go ahead @RoshanMhatre  And don't forget to attach the screenshot of your project while opening a PR

**Comment by RoshanMhatre** [comment]
![Vertical_Image_Slider](https://user-images.githubusercontent.com/54371867/194720054-61650344-8e73-4246-88a3-b770b6ffad10.jpg)

**Comment by RoshanMhatre** [comment]
PR raised for this issue.
Please review.
