### ISSUE TITLE
2_Player_DiceGame

### ISSUE THREAD

**Issue by kunal15112001** [jay-2000/Open-source-hacktoberfest#36]
I have developed a 2 Player Dice Game using HTML5, CSS3, and JS.
Please assign this issue to me and add the 'hacktoberfest-accepted' label to avoid any issues.

**Comment by jay-2000** [comment]
> I have developed a 2 Player Dice Game using HTML5, CSS3, and JS. Please assign this issue to me and add the 'hacktoberfest-accepted' label to avoid any issues.

go ahead @kunal15112001 

don't forget to attach screenshot of your project while opening the PR
