### ISSUE TITLE
New quiz webapp 

### ISSUE THREAD

**Issue by jsvigneshkanna** [jay-2000/Open-source-hacktoberfest#37]
Hey 👋 @jay-2000 , I would like to add quiz website made of (HTML, CSS, JS) which is fun to play.

Please assign this issue to my name
Please add `hacktoberfest-accepted` label, so that I can keep track of all my contributions this month.

Screenshots:
1. Homepage-
![image](https://user-images.githubusercontent.com/42484705/194717899-ba417357-2f79-45d1-a4e0-b76e22e0d6c5.png)

2. Quiz page-
![image](https://user-images.githubusercontent.com/42484705/194717927-a855dc59-53ca-486f-901c-97783be60bf2.png)

Appreciate that

**Comment by jay-2000** [comment]
> Hey 👋 @jay-2000 , I would like to add quiz website made of (HTML, CSS, JS) which is fun to play.
> 
> Please assign this issue to my name Please add `hacktoberfest-accepted` label, so that I can keep track of all my contributions this month.
> 
> Appreciate that

yup @jsvigneshkanna go ahead
don't forget to attach the screenshot of the project while submitting the PR
