### ISSUE TITLE
Add Drum Game

### ISSUE THREAD

**Issue by PumpkinManiac** [jay-2000/Open-source-hacktoberfest#5]
Drum Game using HTML CSS JAVASCRIPT

**Comment by jay-2000** [comment]
@PumpkinManiac go ahead

**Comment by PumpkinManiac** [comment]
Give push access to the repository to upload files related to the project

**Comment by jay-2000** [comment]
> Give push access to the repository to upload files related to the project

Make a folder by name of your project keep your html css and js file inside that folder than open your PR I'll review it and merge you code into my repo
 Ok
