### ISSUE TITLE
Base Changer JavaScript Project

### ISSUE THREAD

**Issue by RahulSahOfficial** [jay-2000/Open-source-hacktoberfest#51]
I want to work on this project where user can changer number to different base by using interactive UI

**Comment by jay-2000** [comment]
> I want to work on this project where user can changer number to different base by using interactive UI

go ahead @RahulSahOfficial i'll assign it to you
keep in mind always sync fork the branch before submitting the PR
Don't forget to mention screenshot of your project while opening/submitting the PR
