### ISSUE TITLE
feat: Stock Management System [Java, Java Swing]

### ISSUE THREAD

**Issue by RoshanMhatre** [jay-2000/Open-source-hacktoberfest#56]
Please assign this issue to me and add the relevant labels.
This is a full-fledged project.

**Comment by jay-2000** [comment]
> Please assign this issue to me and add the relevant labels. This is a full-fledged project.

assigned @RoshanMhatre

**Comment by RoshanMhatre** [comment]
Raised a PR to fix this issue. Please review here: #57

**Comment by jay-2000** [comment]
> Raised a PR to fix this issue. Please review here: #57

@RoshanMhatre just sync fork before opening a new PR
