### ISSUE TITLE
feat: Personal Website including Blog page, projects page, contact page [HTML5, CSS3]

### ISSUE THREAD

**Issue by RoshanMhatre** [jay-2000/Open-source-hacktoberfest#58]
This is a personal website which has clean UI with several pages such as blogs, projects, contact etc.

Please assign this issue to me and add the relevant labels.

**Comment by jay-2000** [comment]
> This is an AI assistant which will analyze previous stock prices and trends and help predict future stock prices to gain profits in the stock market.
> 
> Please assign this issue to me and add the relevant labels.

@RoshanMhatre  go head & push only web based project
(remember : don't forget to sync fork while submitting the new PR and Attach the Screenshot of the project with PR)
