### ISSUE TITLE
Embark- The college journey

### ISSUE THREAD

**Issue by Nitya-Pasrija** [jay-2000/Open-source-hacktoberfest#62]
Hey @jay-2000 
Can you assign this to me?

**Comment by jay-2000** [comment]
> Hey @jay-2000 Can you assign this to me?

yep @Nitya-Pasrija go ahead

**Comment by jay-2000** [comment]
> > Hey @jay-2000 Can you assign this to me?
> 
> yep @Nitya-Pasrija go ahead

don't forget to star the repo
