### ISSUE TITLE
Ayurveda and Yoga

### ISSUE THREAD

**Issue by Nitya-Pasrija** [jay-2000/Open-source-hacktoberfest#63]
Hey @jay-2000 
I was thinking about adding a Yoga Help website 
Can you assign this to me? so that I can add it? :)

**Comment by jay-2000** [comment]
> Hey @jay-2000 I was thinking about adding a Yoga Help website Can you assign this to me? so that I can add it? :)

yeah sure @Nitya-Pasrija go ahead
