### ISSUE TITLE
A mail template.

### ISSUE THREAD

**Issue by mayukh00** [jay-2000/Open-source-hacktoberfest#69]
A mail subscription welcome template.
Hey @jay-2000 , can you assign me this.

**Comment by jay-2000** [comment]
> A mail subscription welcome template. Hey @jay-2000 , can you assign me this.

Yup go ahead @mayukh00

**Comment by mayukh00** [comment]
Perhaps, this was termed excluded by hacktoberfest admins. @jay-2000  :')
