### ISSUE TITLE
Simon game

### ISSUE THREAD

**Issue by yashms25** [jay-2000/Open-source-hacktoberfest#73]
It's a simple game made using HTML, CSS, and javascript. It checks your memory power. Please assign this issue to me.

**Comment by jay-2000** [comment]
> It's a simple game made using HTML, CSS, and javascript. It checks your memory power. Please assign this issue to me.

Sure @yashms25 go ahead

**Comment by jay-2000** [comment]
> > It's a simple game made using HTML, CSS, and javascript. It checks your memory power. Please assign this issue to me.
> 
> Sure @yashms25 go ahead

Dont forget to star⭐ this repository
